### ISSUE TITLE
On chrome mobile, all users were incorrectly shown as muted (and had no audio)

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#229] opened 2022-02-23 11:05 UTC
As seen by t3chguy

**Comment by robertlong** [comment] 2022-02-23 23:20
This issue was filed against v0.0.14 which had a pretty bad bug where toDevice messages that came in out of order would be ignored. It was fixed in v0.0.15. I'm fairly certain this was caused by that bug.

**Closed by robertlong** 2022-02-23 23:20 UTC
