### ISSUE TITLE
Speakerphone mode on iOS

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#128] opened 2021-11-28 00:04 UTC
Was just dogfooding, and discovered that lack of ability to select output device is catastrophic for typical iOS users, as there's no way to select speakerphone as output audio device.  Users reasonably expect speakerphone by default when they don't have a headset plugged in on a video call (and non-speakerphone if it's voice), and need the ability to toggle back and forth otherwise the FTUE on iOS is very problematic.

**Comment by robertlong** [comment] 2021-12-13 18:15
We found that this isn't possible on iOS at the moment... which is fairly frustrating. We need support for picking an output device in Safari.

**Comment by robertlong** [comment] 2021-12-17 00:53
Closing as duplicate of #54

**Closed by robertlong** 2021-12-17 00:53 UTC
