### ISSUE TITLE
Ability to pop out video as OS PIP

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#136] opened 2021-12-08 13:46 UTC
I am checking on iOS so may be misremembering on desktop, but would be amazing to be able to pop out one or more remote videos as an operating system level PIP.

**Comment by SimonBrandner** [comment] 2021-12-08 14:25
I am not really sure this is even possible from the browser :thinking:

**Comment by foxlet** [comment] 2021-12-09 03:01
There does exist a Picture-in-Picture API as part of the Chrome and WebKit for this purpose.

https://googlechrome.github.io/samples/picture-in-picture/

**Comment by ara4n** [comment] 2021-12-09 15:18
Apparently it works automagically on Firefox (you can right-click and pop out).  On Chrome it's greyed out for some reason:

<img width="291" alt="Screenshot 2021-12-09 at 15 17 16" src="https://user-images.githubusercontent.com/1294269/145423462-e54cbcca-7d81-4643-849d-843b293b2df4.png">

**Comment by SimonBrandner** [comment] 2021-12-09 15:20
> Apparently it works automagically on Firefox (you can right-click and pop out).  On Chrome it's greyed out for some reason:
> 
> <img width="291" alt="Screenshot 2021-12-09 at 15 17 16" src="https://user-images.githubusercontent.com/1294269/145423462-e54cbcca-7d81-4643-849d-843b293b2df4.png">
> 

Though I think you can do that only for one video element, not the whole thing, right?

**Comment by ara4n** [comment] 2021-12-09 15:24
yeah, trying to pop out a single video element (or multiple ones, one by one).

**Comment by foxlet** [comment] 2021-12-10 08:47
> Apparently it works automagically on Firefox (you can right-click and pop out). On Chrome it's greyed out for some reason:

Firefox doesn't use the PiP API, they have their own implementation that automatically filters for media elements and lets you pop them out. Chrome relies on each element to implement the PiP API before it becomes available to the user.

Chrome does expose additional features that Firefox PiP does not make available though:
https://googlechrome.github.io/samples/auto-picture-in-picture/ (for PWA)
https://googlechrome.github.io/samples/media-session/video-conferencing.html (for controls in a PiP window)

**Comment by robertlong** [comment] 2021-12-17 00:53
Closing as duplicate of #120 noted, that this isn't possible on Firefox or iOS yet.

**Closed by robertlong** 2021-12-17 00:53 UTC
