### ISSUE TITLE
I suspect 1:1 calls should look like a normal 1:1 call

### ISSUE THREAD

**Issue by ara4n** [vector-im/matrix-video-chat#196] opened 2022-01-28 14:05 UTC
i.e. fullscreen for the speaker, and small thumbnail for local video, rather than the massive local video we have today.

**Comment by SimonBrandner** [comment] 2022-01-31 16:20
Personally, I believe that if this is to be a video-conferencing app the UI should mostly reflect that and shouldn't change way too much depending on the number of users. I would find that inconsistent and potentially confusing

**Comment by babolivier** [comment] 2022-02-07 15:39
Also the current UI (especially in "Speaker" mode) works really well on a 1:1 call when screensharing

**Comment by robertlong** [comment] 2022-02-14 22:54
Agreed! Waiting on designs. Closing as this is a duplicate of #44

**Closed by robertlong** 2022-02-14 22:54 UTC
